export default {
    XML: [ 'tag', 'attributi', 'commenti', 'formattazione' ],

    HTML: [
        'head e intestazioni, metatags, doctype',
        'titoli, paragrafi, testi, corsivo, grassetto',
        'citazioni, code, sup e sub, small, time',
        'elenchi puntati, numerati e custom',
        'tabelle, intestazioni, corpi, colonne e righe, multi riga, multicolonna',
        'link, ancore, percorsi relativi e assoluti',
        'immagini, svg e base64',
        'audio e video',
        'mappe immagine',
        'iframe',
        'form, input, select, checkbox, radio, textarea, button, submit, reset, file',
        'SEO',
    ],

    CSS: [
        'fogli di stile interni ed esterni, stili inline',
        'regole, comenti, direttive',
        'selettori: classi, id, attributi, stati, pseudo classi e pseudo elementi',
        'ereditarietà e conflitti',
        'width, height, overflow',
        'padding, margin, border, outline',
        'background',
        'stile testo',
        'cursore',
        'display, visibility',
        'position e zindex',
        'flex',
        'media query',
    ],

    JS: [
        'file di script esterni e tag script',
        'variabili, costanti, dichiarazioni',
        'stringhe, numeri e altri tipo di dati',
        'espressioni e operatori',
        'conversioni fra i tipi',
        'array e oggetti, metodi',
        'controllo di flusso (if/then/else, switch/case, while, do while, for, break e continue)',
        'global e local: scope',
        'Classe Math',
        'Regex e match',
        'Date e orari',
        'JSON',
        'metodi avanzati su array e oggetti (map, reduce, filter)',
        'ES6, Babel, classi, arrow function',
        'DOM, window, query e manipolazione',
        'Eventi, callback, promise, varianti es6',
        'AJAX, fetch: ieri, oggi, domani',
        'jQuery: querying, eventi, manipolazioni',
    ],

    'React': [
        'fondamenti component driven, vs jQuery, vs Angular',
        'tools sviluppo: accenni gulp, npm, npx, node, react-scripts',
        'JSX, map, reduce, ternary, expressions',
        'componenti e props',
        'gestione state e immutability',
        'component lifecycle',
        'hooks: useState, useEffect, useMemo, useContext',
        'sample react app',
        'navigazione con react router',
    ],

    'Strumenti sviluppo': [
        'Editor',
        'Terminale, zsh',
        'ssh, deploy, continuous integration',
        'Git',
        'NPM, Node',
        'DNS',
        'Apache, PHP, MySql',
        'Postman',
    ]
}